### ISSUE TITLE
Use a temporary file while generating the feed

### ISSUE THREAD

**Issue by benoit-apk** [shoppingflux/php-feed-generator#2]
Only write the feed to the given URI when everything has been (correctly) generated, so that it is impossible to end up with an incomplete feed

**Comment by ronan-gloo** [comment]
The simplest way to do that is to copy the feed once generated to the final destination.

But we can support temporary file, I'm just not sure about how to implement it, maybe when declaring the uri, where second parameter may be the temporary file : 

```
$generator->setUri('final_file.xml', 'temp.xml');
```

Can you tell me what exactly is your scenario here ?
Thanks

**Comment by benoit-apk** [comment]
> The simplest way to do that is to copy the feed once generated to the final destination.

This is actually the solution I ended up with :)

Anyway, closing this issue as I agree on the fact that it makes sense to let this responsibility on the user.
