### ISSUE TITLE
Do no export the quantity for parent products

### ISSUE THREAD

**Issue by benoit-apk** [shoppingflux/php-feed-generator#3]
The quantity is currently exported for all products, including those with variations, and even when none is given. Shouldn't it be skipped instead, at least for parent products ?

**Comment by ronan-gloo** [comment]
@benoit-apk 

Quantity is a mandatory field, it will be set to 0 if none. Note that Shopping Feed uses variation quantity when exists, or fallback on parent's one if none, that allow some merchants to define one quantity for all variations
